### ISSUE TITLE
`allas_conf_scope:59: number expected` when sourcing `allas_conf`

### ISSUE THREAD

**Issue by v-iashin** [CSCfi/allas-cli-utils#2]
Hi. Thanks for documenting access to Allas from non-CSC infrastructure.

## Problem
It seems that the script does not work with `zsh` 

## Details
I tried to set up access to Allas from another Linux machine by creating `allas_conf` file and then sourcing it in `zsh`:
```zsh
zsh
source allas_conf --mode s3cmd --user my_csc_user_name
# fails with `allas_conf_scope:59: number expected`
```

I had this problem on two machines + my colleague also encountered it at some point.

## Our work-around:
Switch to `bash`:
```zsh
bash
```
Config the Allas connection
```zsh
source allas_conf --mode s3cmd --user my_csc_user_name
```
This will prompt a password to Allas (CSC). If it fails with `Error: openstack command not found!` you need to install `python-openstack` first and then try again (e.g. in a python environment). 

Next, switch back to `zsh`
```bash
zsh
```
Try if this works
```zsh
s3cmd ls
```
`s3cmd` sometimes is not installed on the machine and should be installed manually (also e.g. in the pyenv/conda).

**Comment by kkmattil** [comment]
Documentation updated.
