### ISSUE TITLE
command to copy *local* files to allas

### ISSUE THREAD

**Issue by iburunat** [CSCfi/allas-cli-utils#5]
Hi! 

To the point:  `a-put is used to upload data from the disk environment of Mahti and Puhti to the Allas storage environment`

Is there a command to upload **local** files to Allas?

I tried using `rclone`: 

```shell
§ rclone copyto /Users/user/Desktop/data.mat  allas:testdata
```

and also `s3cmd`:
```shell
§ s3cmd put "/Users/user/Desktop/data.mat"  s3://testdata
```

unsuccessfully.

Thanks for your help.

**Comment by kkmattil** [comment]
You can use a-put, as well as rclone or s3cmd too, to move data between your local computer and
Allas. However you need to have a CSC user account and project and you need to configure the connection between your local
machine and Allas before you start moving data.

After you have installed allas-cli-utils to your local computer you can use allas_conf script to set up Swift  or S3 based connection:
 Swift: 
   source allas-cli-utils/allas_conf -u your-csc-user-account

 S3:
   source allas-cli-utils/allas_conf -u your-csc-user-account -m S3

**Comment by iburunat** [comment]
Thanks. I git cloned the repo, and continued to set up the connection as indicated (tried both SWIFT and S3), unsuccessfully:
![image](https://user-images.githubusercontent.com/26675866/176543415-3d695bb0-877c-4de1-9250-65a422b3ca87.png)

**Comment by iburunat** [comment]
I was using zsh, thus the error.
Now I managed to move on a bit, but the tool's commands aren't found:

![image](https://user-images.githubusercontent.com/26675866/176549291-e4712edf-7ac7-4a4d-8284-63c59bf3bdf9.png)

**Comment by iburunat** [comment]
Seems the path wasn't added to PATH.
This is the last error I get:

![image](https://user-images.githubusercontent.com/26675866/176553744-17d7d02f-ed9d-4bca-9a7d-9013359518c0.png)

**Comment by kkmattil** [comment]
These scripts work in bash shell. You are probably using zsh here.

**Comment by kkmattil** [comment]
Then a second issue is that at the moment a-list does not support S3 connections.
Use 
  rclone ls s3allas: 

in stead.

**Comment by iburunat** [comment]
Thanks for your help, I was using `bash`, it was the second issue (`a-list` not working in S3).
Now it seems to work.
